### ISSUE TITLE
Failed to execute RasterToPoint, possible empty feature class (error 010151)

### ISSUE THREAD

**Issue by javinav** [james-roden/ArcGIS-RGB-to-Z-Tool#1]
I'm processing a world map (from https://s3-eu-west-1.amazonaws.com/globalwindatlas/posters/World_PD.png) at 0.01 degree resolution, which I've georeferenced to WGS-84 (rectified). The code runs well up to "Numpy array re-stacked and z-value function ran across channel axis". 

In the following step "Executing: RasterToPoint (...)RGBtoZ_Pnt.shp Value" it fails with error:

> Failed to execute (RasterToPoint).
> 
> ArcPy ERRORS:
> Executing: RasterToPoint C:\temp_javi\RGBtoZ_Ras C:\temp_javi\RGBtoZ_Pnt.shp Value
> Start Time: Mon Jul 30 14:40:35 2018
> ERROR 010151: No features found in C:\temp_javi\rgbtoz_pnt.shp. Possible empty feature class.
> Failed to execute (RasterToPoint).
> Failed at Mon Jul 30 14:40:35 2018 (Elapsed Time: 0.21 seconds)
> 
> in_memory intermediate files deleted.
> Completed script RGB-to-Z...
> Failed to execute (RGB-to-Z).
> Failed at Mon Jul 30 14:40:35 2018 (Elapsed Time: 8 minutes 31 seconds)

I am running ArcGIS 10.3 in a Windows 7 enterprise machine. No other python installation in the machine. 

Btw, this is a very nice tool. 

Thanks,

Javi

**Comment by james-roden** [comment]
Hi Javi,

I just tried running it on my machine with the _World_PD.png_ image and it works without error. It seems the error is being thrown by the arcpy tool -- seriously had enough of those! Ha. 
Have you tried turning off background geoprocessing? I understand this can sometimes cause spurious errors like this.
Also, may I see how you formatted the text document?

Regardless -- I don't think this image is the correct _"quality"_ for this tool. I ran it for the blue areas and you can see it misses quite a lot. The RGB values don't match up with the ones in the legend.

![img1](https://user-images.githubusercontent.com/17338239/43394581-1feb699c-93f3-11e8-868b-6d966e34f2b7.png)

James

**Comment by javinav** [comment]
Hi James,

Thanks for your quick response. I'll try turning off background geoprocessing but I note what you say about it missing areas. It might not be such a big deal though, I might be able to work around it. I have a feeling the actual map looks lighter than the legend, like they've made it more transparent.

This is how I wrote the text file:

159 242 252 25
130 226 250 50
81 178 226 75
61 144 208 100
45 119 190 125
31 95 175 150
19 71 157 175
33 83 109 200
19 95 75 225
20 106 47 250
20 119 25 275
20 133 7 300
49 154 9 325
86 174 11 350
130 192 14 375
184 192 14 400
254 239 20 450
252 186 13 500
250 139 8 550
248 98 4 600
246 65 1 650
244 30 0 700
231 18 0 750
220 9 0 800
209 3 0 850
194 0 0 900
162 0 1 1000
145 0 5 1100
127 0 10 1200
112 0 18 1300
96 0 27 1400

Cheers

Javi

**Comment by james-roden** [comment]
Hi Javi,

Text format looks fine :)

Yes, I think you're right. the light blue is certainly more towards 'white' than the legend's equivalent. 

Let me know if you're still having issues with the Raster_to_Point tool

James

**Comment by javinav** [comment]
Thanks James, no worries I'll let you know either way!

Cheers

J

**Comment by javinav** [comment]
Hi James,

It seems disabling background geoprocessing did the job, but as you said results weren't great. I'll try a complementary approach and if I get it to work I'll let you know.

J

**Comment by james-roden** [comment]
Ah good. Perhaps at some point I'll find a way for it to work without using arcpy!

**Comment by javinav** [comment]
Good news James. There's a reasonable way to process the image so your tool will work, which means that this will have a wide appeal. So in this case the problem with the reference map is that there are around 140.000 unique RGB values (the legend only defines 32 different values). You definitely don't need that level of data accuracy anyway as the uncertainty of modelling will make that level of detail unnecessary. Already the authors hint at the accuracy of the model by the legend chosen. If you take freely-available software such as Xnview (or you can do this in Python) you can pick the number of unique colours that you want the image to have. In this case I find 32-40 colours works perfectly well for my application and the loss of detail is tolerable. Then, still in Xnview or Python, you can extract the colour palette and start deciding how to code the rgb to z conversion in the text file. Works well!

**Comment by james-roden** [comment]
Hi Javi,

Great idea! So for example in XnView, you are using 'Change color depth' to adjust the number of colours to 32? 

If you don't mind, would love to see the outcome when you run the RGB-to-Z tool.

James

**Comment by javinav** [comment]
In my version of XnView there's an option called "convert to colours" under "Image" and you can nominate the number of colours you want and enable/disable dithering (which I disabled). 

Sure, happy to share. This is the processed image before:

![before](https://user-images.githubusercontent.com/36751494/43558317-3364915a-964c-11e8-8896-abb3be749f2f.png)

and after applying RGB to Z:

![after_rgbtoz](https://user-images.githubusercontent.com/36751494/43558335-5414a17e-964c-11e8-8bc3-dfc10aae8307.png)

Cheers

Javi

**Comment by james-roden** [comment]
If anyone reading this would like a Python way of reducing colours in the image:
It's possible using Pillow :)
